language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

services:
  - redis-server

sudo: false
dist: trusty

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - sh -c "if [ $TRAVIS_PHP_VERSION != 'hhvm' ]; then phpenv config-add ./tests/travis/php.ini; fi"
  - composer install

script:
  - $TRAVIS_BUILD_DIR/vendor/phpunit/phpunit/phpunit
